version: "3.8"
services:
  postgres-db:
    image: postgres:15.2
    restart: on-failure
    env_file: .env
    environment:
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
      - 'POSTGRES_DB=$POSTGRES_DATABASE'
    ports:
      - $POSTGRES_EXPOSED_PORT:$POSTGRES_INTERNAL_PORT
  document-system-app:
    depends_on:
      - postgres-db
    build: ./
    restart: on-failure
    tty: true
    env_file:
      - .env
    ports:
      - $APP_EXPOSED_PORT:$APP_INTERNAL_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres-db:$POSTGRES_INTERNAL_PORT/$POSTGRES_DATABASE?useSSL=false",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "create"
      }'